# Solution to Case Study
## 2


$scores = \begin{bmatrix} 80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65 \end{bmatrix}$


In [42]:
import numpy as np
scores = np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70, 60, 65]])
print(f"Initial Scores Matrix \n{scores}")

# Sum of Rows
answer3_2 = np.sum(scores, axis=1)
i = 1
print(f"\nSum by row = \n{answer3_2}\n")
for score in answer3_2:
    print(f"Score for Student {i} = {score}")
    i+=1


# Weight applied to Maths Column
copy = scores.copy()
copy[:, 0] = 2 * copy[:, 0]
print(f"\n After Applying x2 to Maths : \n{copy}")

# Average Score per subject = Column wise Mean
answer3_4 = np.mean(copy, axis=0)
print(f"\n Average Score per Subject: \n{answer3_4}")

# Final Grades Using Matrix Multiplication
weight_vector = np.array([0.5, 0.3, 0.2])
answer3_5 = np.dot(copy, weight_vector)
print(f"\n Final Scores After Matrix Multiplication: \n{answer3_5}")

#
answer3_6 = np.diff(copy, axis=0)
print(f"\nComparing Student Scores(By Column): \n{answer3_6}")




Initial Scores Matrix 
[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]

Sum by row = 
[240 220 275 195]

Score for Student 1 = 240
Score for Student 2 = 220
Score for Student 3 = 275
Score for Student 4 = 195

 After Applying x2 to Maths : 
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]

 Average Score per Subject: 
[152.5   75.75  80.5 ]

 Final Scores After Matrix Multiplication: 
[119.  100.5 139.8 101. ]

Comparing Student Scores(By Column): 
[[-40  15 -15]
 [ 70   3  17]
 [-50 -28 -27]]


# 5. Add -On Excercises



$scores\_matrix = \begin{bmatrix} 80 & 70 & 90 & 80 \\ 60 & 85 & 75 & 95 \\ 95 & 88 & 92 & 70 \\ 70 & 60 & 65 &85 \\ 90 & 40 & 75 & 65 \end{bmatrix}$

Student &emsp;    Math       English      Science     Computer

student1

student2

student3

student4

student5



In [43]:
scores_matrix = np.array([[80, 70, 90, 80], 
                          [60, 85, 75, 95], 
                          [95, 88, 92, 70], 
                          [70, 60, 65, 85], 
                          [90, 40, 75, 65]])

print("Initial Scores Matrix \n", scores_matrix)


Initial Scores Matrix 
 [[80 70 90 80]
 [60 85 75 95]
 [95 88 92 70]
 [70 60 65 85]
 [90 40 75 65]]


### 1. Each Student's Total Score and Average Per Subect

In [49]:
total_scores_per_student = np.sum(scores_matrix, axis=1)
print(f"\nSum by row = \n{total_scores_per_student}\n")

i = 1
for score in total_scores_per_student:
    print(f"Total Score for Student {i} = {score}")
    i+=1
    
# Average Score per subject = Column wise Mean
average_per_subject = np.mean(scores_matrix, axis=0)
print(f"\n Average Score per Subject: \n{average_per_subject}")
print(f"Average Score for Mathematics = {average_per_subject[0]}")
print(f"Average Score for English = {average_per_subject[1]}")
print(f"Average Score for Science = {average_per_subject[2]}")
print(f"Average Score for Computer = {average_per_subject[3]}")



Sum by row = 
[320 315 345 280 270]

Total Score for Student 1 = 320
Total Score for Student 2 = 315
Total Score for Student 3 = 345
Total Score for Student 4 = 280
Total Score for Student 5 = 270

 Average Score per Subject: 
[79.  68.6 79.4 79. ]
Average Score for Mathematics = 79.0
Average Score for English = 68.6
Average Score for Science = 79.4
Average Score for Computer = 79.0


### 2. Apply Weight of 3x to Science 

i.e. $scores\_matrix [2]\times 3$

In [51]:
scores_copy = scores_matrix.copy()
# Apply 3x to Science Column
scores_copy[:, 2] = 3 * scores_copy[:, 2]
print("\n Matrix after 3 * Science Column: \n", scores_copy)
#Recompute Totals Per Student
new_total_scores_per_student = np.sum(scores_copy, axis=1)
print(f"\nSum by row = \n{new_total_scores_per_student}\n")

i = 1
for score in new_total_scores_per_student:
    print(f"New Total Score for Student {i} = {score}")
    i+=1



 Matrix after 3 * Science Column: 
 [[ 80  70 270  80]
 [ 60  85 225  95]
 [ 95  88 276  70]
 [ 70  60 195  85]
 [ 90  40 225  65]]

Sum by row = 
[500 465 529 410 420]

New Total Score for Student 1 = 500
New Total Score for Student 2 = 465
New Total Score for Student 3 = 529
New Total Score for Student 4 = 410
New Total Score for Student 5 = 420


### Define new weights for grading and Compute Final Grades
e.g. $weights\_vector\ = [0.4, 0.2, 0.3, 0.1] $


In [54]:
# Final Grades Using Matrix Multiplication
final_weight_vector = np.array([0.4, 0.2, 0.3, 0.1])
final_grades = np.dot(scores_copy, final_weight_vector)
print(f"\n Final Scores After Matrix Multiplication: \n{final_grades} \n")

i=1
for score in final_grades:
    print(f"Final Grade for Student {i}: {score}")
    i+=1


 Final Scores After Matrix Multiplication: 
[135.  118.  145.4 107.  118. ] 

Final Grade for Student 1: 135.0
Final Grade for Student 2: 118.0
Final Grade for Student 3: 145.4
Final Grade for Student 4: 107.0
Final Grade for Student 5: 118.0
