# Matrix Operations: Class Task 2

## Part a:

**Matrix A** has **2 rows** and **3 columns**, making it a $2 \times 3$ matrix.

**Matrix B** has **3 rows** and **2 columns**, making it a a $3 \times 2$ matrix.


## Part b:

For **AB**, the number of columns in **A** (which is 3) matches the number of rows in **B** (which is 3).
Thus, **AB** can be multiplied.

For **BA**, the number of columns in **B** (which is 2) matches the number of rows in **A** (which is 2).

Thus, **BA** can be multiplied.

Therefore, both **AB** and **BA** can be multiplied.

## Part c
#### Step-by-step calculation of AB
The resulting matrix will be a $2 \times 2$ matrix.

$AB = \begin{bmatrix} 2 & -1 & 3 \\ 0 & 4 & 1 \end{bmatrix} \begin{bmatrix} 1 & 2 \\ -2 & 0 \\ 5 & -3 \end{bmatrix} = \begin{bmatrix} c_{11} & c_{12} \\ c_{21} & c_{22} \end{bmatrix}$

- **$c_{11}$**: (2)(1) + (-1)(-2) + (3)(5) = 2 + 2 + 15 = **19**
- **$c_{12}$**: (2)(2) + (-1)(0) + (3)(-3) = 4 + 0 - 9 = **-5**
- **$c_{21}$**: (0)(1) + (4)(-2) + (1)(5) = 0 - 8 + 5 = **-3**
- **$c_{22}$**: (0)(2) + (4)(0) + (1)(-3) = 0 + 0 - 3 = **-3**


$AB = \begin{bmatrix} 19 & -5 \\ -3 & -3 \end{bmatrix}$

#### Step-by-step calculation of BA

The resulting matrix will be a $3 \times 3$ matrix. \n
$BA = \begin{bmatrix} 1 & 2 \\ -2 & 0 \\ 5 & -3 \end{bmatrix} \begin{bmatrix} 2 & -1 & 3 \\ 0 & 4 & 1 \end{bmatrix} = \begin{bmatrix} d_{11} & d_{12} & d_{13} \\ d_{21} & d_{22} & d_{23} \\ d_{31} & d_{32} & d_{33} \end{bmatrix}$


- **$d_{11}$**: (1)(2) + (2)(0) = 2 + 0 = **2**
- **$d_{12}$**: (1)(-1) + (2)(4) = -1 + 8 = **7**
- **$d_{13}$**: (1)(3) + (2)(1) = 3 + 2 = **5**
- **$d_{21}$**: (-2)(2) + (0)(0) = -4 + 0 = **-4**
- **$d_{22}$**: (-2)(-1) + (0)(4) = 2 + 0 = **2**
- **$d_{23}$**: (-2)(3) + (0)(1) = -6 + 0 = **-6**
- **$d_{31}$**: (5)(2) + (-3)(0) = 10 + 0 = **10**
- **$d_{32}$**: (5)(-1) + (-3)(4) = -5 - 12 = **-17**
- **$d_{33}$**: (5)(3) + (-3)(1) = 15 - 3 = **12**

$BA = \begin{bmatrix} 2 & 7 & 5 \\ -4 & 2 & -6 \\ 10 & -17 & 12 \end{bmatrix}$

In [11]:
## Solution using numpy as taught
import numpy as np

A = np.array([[2, -1, 3],
              [0, 4, 1]])
B = np.array([[1, 2],
              [-2, 0],
              [5, -3]])

AB = A.dot(B)
BA = B.dot(A)

print("A (shape):", A.shape)
print(A)
print('\nB (shape):', B.shape)
print(B)

print('\nAB (shape):', AB.shape)
print(AB)

print('\nBA (shape):', BA.shape)
print(BA)


A (shape): (2, 3)
[[ 2 -1  3]
 [ 0  4  1]]

B (shape): (3, 2)
[[ 1  2]
 [-2  0]
 [ 5 -3]]

AB (shape): (2, 2)
[[19 -5]
 [-3 -3]]

BA (shape): (3, 3)
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
