## 1) Initial matrix
$scores = \begin{bmatrix} 80 & 70 & 90 \\ 60 & 85 & 75 \\ 95 & 88 & 92 \\ 70 & 60 & 65 \end{bmatrix}$


## 2) Sum of rows (total score per student)


- Student 1: 80 + 70 + 90 = 240  
- Student 2: 60 + 85 + 75 = 220  
- Student 3: 95 + 88 + 92 = 275  
- Student 4: 70 + 60 + 65 = 195

So the row sums are: `[240, 220, 275, 195]`

## 3) Apply weight to the Maths column (multiply first column by 2)

- Student 1: Maths 80 * 2 -> 160. New row: `[160, 70, 90]`  
- Student 2: Maths 60 * 2 -> 120. New row: `[120, 85, 75]`  
- Student 3: Maths 95 * 2 -> 190. New row: `[190, 88, 92]`  
- Student 4: Maths 70 * 2 -> 140. New row: `[140, 60, 65]`

New Matrix is: `[[160, 70, 90], [120, 85, 75], [190, 88, 92], [140, 60, 65]]`

## 4) Average score per subject (column-wise mean)


- Maths mean = (160 + 120 + 190 + 140) / 4 = 610 / 4 = 152.5  
- English mean = (70 + 85 + 88 + 60) / 4 = 303 / 4 = 75.75  
- Science mean = (90 + 75 + 92 + 65) / 4 = 322 / 4 = 80.5

So the column-wise means are: `[152.5, 75.75, 80.5]`

## 5) Final grades using matrix multiplication (weighted sum)

weight vector: `weight_vector = [0.5, 0.3, 0.2]`.

- Student 1: `160*0.5 + 70*0.3 + 90*0.2 = 80 + 21 + 18 = 119`  
- Student 2: `120*0.5 + 85*0.3 + 75*0.2 = 60 + 25.5 + 15 = 100.5`  
- Student 3: `190*0.5 + 88*0.3 + 92*0.2 = 95 + 26.4 + 18.4 = 139.8`  
- Student 4: `140*0.5 + 60*0.3 + 65*0.2 = 70 + 18 + 13 = 101`

So the final scores are: `[119.0, 100.5, 139.8, 101.0]`

## 6) Comparing students (consecutive differences by column)

We compute differences between consecutive students (row-wise differences).

Manually:
- Student2 - Student1 = `[120-160, 85-70, 75-90]` = `[-40, 15, -15]`  
- Student3 - Student2 = `[190-120, 88-85, 92-75]` = `[70, 3, 17]`  
- Student4 - Student3 = `[140-190, 60-88, 65-92]` = `[-50, -28, -27]`

So the differences matrix is:
`[[-40, 15, -15],
  [70, 3, 17],
  [-50, -28, -27]]`


## Verification With Numpy 

In [25]:
import numpy as np
scores = np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70, 60, 65]])
print(f"Initial Scores Matrix \n{scores}")

# Sum of Rows
answer3_2 = np.sum(scores, axis=1)
i = 1
print(f"\nSum by row = \n{answer3_2}\n")
for score in answer3_2:
    print(f"Score for Student {i} = {score}")
    i+=1


# Weight applied to Maths Column
copy = scores.copy()
copy[:, 0] = 2 * copy[:, 0]
print(f"\n After Applying x2 to Maths : \n{copy}")

# Average Score per subject = Column wise Mean
answer3_4 = np.mean(copy, axis=0)
print(f"\n Average Score per Subject: \n{answer3_4}")

# Final Grades Using Matrix Multiplication
weight_vector = np.array([0.5, 0.3, 0.2])
answer3_5 = np.dot(copy, weight_vector)
print(f"\n Final Scores After Matrix Multiplication: \n{answer3_5}")

# Comparing Students (Vector Subtraction)
answer3_6 = np.diff(copy, axis=0)
print(f"\nComparing Student Scores(By Column): \n{answer3_6}")




Initial Scores Matrix 
[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]

Sum by row = 
[240 220 275 195]

Score for Student 1 = 240
Score for Student 2 = 220
Score for Student 3 = 275
Score for Student 4 = 195

 After Applying x2 to Maths : 
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]

 Average Score per Subject: 
[152.5   75.75  80.5 ]

 Final Scores After Matrix Multiplication: 
[119.  100.5 139.8 101. ]

Comparing Student Scores(By Column): 
[[-40  15 -15]
 [ 70   3  17]
 [-50 -28 -27]]


# 
# 
#
#
#

# 5. Add -On Excercises



$scores\_matrix = \begin{bmatrix} 80 & 70 & 90 & 80 \\ 60 & 85 & 75 & 95 \\ 95 & 88 & 92 & 70 \\ 70 & 60 & 65 &85 \\ 90 & 40 & 75 & 65 \end{bmatrix}$

Student &emsp;    Math &emsp;      English &emsp;     Science &emsp;     Computer

student1

student2

student3

student4

student5



In [26]:
scores_matrix = np.array([[80, 70, 90, 80], 
                          [60, 85, 75, 95], 
                          [95, 88, 92, 70], 
                          [70, 60, 65, 85], 
                          [90, 40, 75, 65]])

print("Initial Scores Matrix \n", scores_matrix)


Initial Scores Matrix 
 [[80 70 90 80]
 [60 85 75 95]
 [95 88 92 70]
 [70 60 65 85]
 [90 40 75 65]]


## 1. Each Student's Total Score and Average Per Subect

#### a) Total scores per student (row sums)

- Student 1: 80 + 70 + 90 + 80 = 320  
- Student 2: 60 + 85 + 75 + 95 = 315  
- Student 3: 95 + 88 + 92 + 70 = 345  
- Student 4: 70 + 60 + 65 + 85 = 280  
- Student 5: 90 + 40 + 75 + 65 = 270  

So totals = `[320, 315, 345, 280, 270]`


#### b) Average score per subject (column-wise mean)


- Maths average = (80+60+95+70+90)/5 = 79  
- English average = (70+85+88+60+40)/5 = 68.6  
- Science average = (90+75+92+65+75)/5 = 79.4  
- Computer average = (80+95+70+85+65)/5 = 79  

So averages = `[79, 68.6, 79.4, 79]`


In [27]:
total_scores_per_student = np.sum(scores_matrix, axis=1)
print(f"\nSum by row = \n{total_scores_per_student}\n")

i = 1
for score in total_scores_per_student:
    print(f"Total Score for Student {i} = {score}")
    i+=1
    
# Average Score per subject = Column wise Mean
average_per_subject = np.mean(scores_matrix, axis=0)
print(f"\n Average Score per Subject: \n{average_per_subject}")
print(f"Average Score for Mathematics = {average_per_subject[0]}")
print(f"Average Score for English = {average_per_subject[1]}")
print(f"Average Score for Science = {average_per_subject[2]}")
print(f"Average Score for Computer = {average_per_subject[3]}")



Sum by row = 
[320 315 345 280 270]

Total Score for Student 1 = 320
Total Score for Student 2 = 315
Total Score for Student 3 = 345
Total Score for Student 4 = 280
Total Score for Student 5 = 270

 Average Score per Subject: 
[79.  68.6 79.4 79. ]
Average Score for Mathematics = 79.0
Average Score for English = 68.6
Average Score for Science = 79.4
Average Score for Computer = 79.0


## 2. Apply Weight of 3x to Science and recompute totals

i.e. $scores\_matrix [2]\times 3$

 
- Student 1: 80 + 70 + 270 + 80 = 500  
- Student 2: 60 + 85 + 225 + 95 = 465  
- Student 3: 95 + 88 + 276 + 70 = 529  
- Student 4: 70 + 60 + 195 + 85 = 410  
- Student 5: 90 + 40 + 225 + 65 = 420  

So new totals = `[500, 465, 529, 410, 420]`


In [28]:
scores_copy = scores_matrix.copy()
# Apply 3x to Science Column
scores_copy[:, 2] = 3 * scores_copy[:, 2]
print("\n Matrix after 3 * Science Column: \n", scores_copy)
#Recompute Totals Per Student
new_total_scores_per_student = np.sum(scores_copy, axis=1)
print(f"\nSum by row = \n{new_total_scores_per_student}\n")

i = 1
for score in new_total_scores_per_student:
    print(f"New Total Score for Student {i} = {score}")
    i+=1



 Matrix after 3 * Science Column: 
 [[ 80  70 270  80]
 [ 60  85 225  95]
 [ 95  88 276  70]
 [ 70  60 195  85]
 [ 90  40 225  65]]

Sum by row = 
[500 465 529 410 420]

New Total Score for Student 1 = 500
New Total Score for Student 2 = 465
New Total Score for Student 3 = 529
New Total Score for Student 4 = 410
New Total Score for Student 5 = 420


## 3. Define new weights for grading and Compute Final Grades
e.g. $weights\_vector\ = [0.4, 0.2, 0.3, 0.1] $


- Student 1: `80×0.4 + 70×0.2 + 270×0.3 + 80×0.1`
  - = `32 + 14 + 81 + 8`  
  - = `135`

- Student 2: `60×0.4 + 85×0.2 + 225×0.3 + 95×0.1`  
  - = `24 + 17 + 67.5 + 9.5`  
  - = `118`

- Student 3: `95×0.4 + 88×0.2 + 276×0.3 + 70×0.1`  
  - = `38 + 17.6 + 82.8 + 7`  
  - = `145.4`

- Student 4: `70×0.4 + 60×0.2 + 195×0.3 + 85×0.1`  
  - = `28 + 12 + 58.5 + 8.5`  
  - = `107`

- Student 5: `90×0.4 + 40×0.2 + 225×0.3 + 65×0.1`  
  - = `36 + 8 + 67.5 + 6.5`  
  - = **118**

Final Results = `[135, 118, 145.4, 107, 118]`


In [29]:
# Final Grades Using Matrix Multiplication
final_weight_vector = np.array([0.4, 0.2, 0.3, 0.1])
final_grades = np.dot(scores_copy, final_weight_vector)
print(f"\n Final Scores After Matrix Multiplication: \n{final_grades} \n")

i=1
for score in final_grades:
    print(f"Final Grade for Student {i}: {score}")
    i+=1


 Final Scores After Matrix Multiplication: 
[135.  118.  145.4 107.  118. ] 

Final Grade for Student 1: 135.0
Final Grade for Student 2: 118.0
Final Grade for Student 3: 145.4
Final Grade for Student 4: 107.0
Final Grade for Student 5: 118.0


## 4. Compare Student3 and Student4, who performed better?

Matrix slice (rows 2–3, all columns):

Student 3 = [95, 88, 92, 70]  
Student 4 = [70, 60, 65, 85]

Difference (Student4 – Student3):  
= [70-95, 60-88, 65-92, 85-70]  
= [-25, -28, -27, 15]

Interpretation:  
- Negative = Student 3 performed better.  
- Positive = Student 4 performed better.

So:  
- Maths: Student 3 better by 25  
- English: Student 3 better by 28  
- Science: Student 3 better by 27  
- Computer: Student 4 better by 15


In [30]:
student3_and_4 = scores_matrix[2:4, :]
print(f"Scores of Student 3 and 4 only: \n {student3_and_4}")
diff_matrix = np.diff(student3_and_4, axis=0)
print(f"\nComparing Student 3 and 4 Scores(By Subject): \n{diff_matrix}")

i=0
for diff in diff_matrix[0]:
    if diff < 0:
        print(f"Student 3 performed better in Subject {i+1} by {abs(diff)} marks")
    else: 
        print(f"Student 4 performed better in Subject {i+1} by {abs(diff)} marks")
        
    i+=1

Scores of Student 3 and 4 only: 
 [[95 88 92 70]
 [70 60 65 85]]

Comparing Student 3 and 4 Scores(By Subject): 
[[-25 -28 -27  15]]
Student 3 performed better in Subject 1 by 25 marks
Student 3 performed better in Subject 2 by 28 marks
Student 3 performed better in Subject 3 by 27 marks
Student 4 performed better in Subject 4 by 15 marks
