## Question 1
**Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.**

In [7]:
import numpy as np

# set a seed for reproducibility
np.random.seed(42)

# create the array
A = np.random.randint(1, 51, size=(6,6))
print("6x6 Array:")
print(A)

6x6 Array:
[[39 29 15 43  8 21]
 [39 19 23 11 11 24]
 [36 40 24  3 22  2]
 [24 44 30 38  2 21]
 [33 12 22 44 25 49]
 [27 42 28 16 15 47]]


## Question 2
**Extract the following:**
- The first two rows
- The last three columns
- All even numbers in the array

In [8]:
# first two rows
first_two_rows = A[:2, :]
print("First two rows:")
print(first_two_rows)

# last three columns
last_three_cols = A[:, -3:]
print("\nLast three columns:")
print(last_three_cols)

# all even numbers
even_numbers = A[A % 2 == 0]
print("\nAll even numbers:")
print(even_numbers)

First two rows:
[[39 29 15 43  8 21]
 [39 19 23 11 11 24]]

Last three columns:
[[43  8 21]
 [11 11 24]
 [ 3 22  2]
 [38  2 21]
 [44 25 49]
 [16 15 47]]

All even numbers:
[ 8 24 36 40 24 22  2 24 44 30 38  2 12 22 44 42 28 16]


## Question 3
**Array transformations:**
- Reshape the array into a 3D (3,2,6) array
- Flatten the reshaped array back to 1D


In [9]:
reshaped = A.reshape(3,2,6)
print("Reshaped (3,2,6) array:")
print(reshaped)

flattened = reshaped.flatten()
print("\nFlattened back to 1D:")
print(flattened)

Reshaped (3,2,6) array:
[[[39 29 15 43  8 21]
  [39 19 23 11 11 24]]

 [[36 40 24  3 22  2]
  [24 44 30 38  2 21]]

 [[33 12 22 44 25 49]
  [27 42 28 16 15 47]]]

Flattened back to 1D:
[39 29 15 43  8 21 39 19 23 11 11 24 36 40 24  3 22  2 24 44 30 38  2 21
 33 12 22 44 25 49 27 42 28 16 15 47]




## Question 4
**Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40 (step of 10).**

In [11]:
I = np.identity(4, dtype=int)
diag_values = np.arange(10, 41, 10)
np.fill_diagonal(I, diag_values)

print("Modified identity matrix:")
print(I)

Modified identity matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


## Question 5
**Matrix multiplication between:**
- A 3x4 matrix of random integers (1-10)
- A 4x3 matrix of random integers (1-10)

In [12]:
M1 = np.random.randint(1, 11, size=(3,4))
M2 = np.random.randint(1, 11, size=(4,3))

print("Matrix 1 (3x4):")
print(M1)
print("\nMatrix 2 (4x3):")
print(M2)

product = np.matmul(M1, M2)
print("\nMatrix multiplication result (3x3):")
print(product)

Matrix 1 (3x4):
[[3 7 4 9]
 [3 5 3 7]
 [5 9 7 2]]

Matrix 2 (4x3):
[[ 4  9  2]
 [10  9 10]
 [ 5  2  4]
 [ 7  8  3]]

Matrix multiplication result (3x3):
[[165 170 119]
 [126 134  89]
 [159 156 134]]


## Question 6
**Function that transforms a 2D array:**  
- Even numbers → squared  
- Odd numbers → -1

In [13]:
def transform_array(arr):
    # create a copy so as not to modify original
    new_arr = arr.copy()
    new_arr[new_arr % 2 == 0] = new_arr[new_arr % 2 == 0] ** 2
    new_arr[new_arr % 2 == 1] = -1
    return new_arr

print("Original array:")
print(A)
print("\nTransformed array:")
print(transform_array(A))

Original array:
[[39 29 15 43  8 21]
 [39 19 23 11 11 24]
 [36 40 24  3 22  2]
 [24 44 30 38  2 21]
 [33 12 22 44 25 49]
 [27 42 28 16 15 47]]

Transformed array:
[[  -1   -1   -1   -1   64   -1]
 [  -1   -1   -1   -1   -1  576]
 [1296 1600  576   -1  484    4]
 [ 576 1936  900 1444    4   -1]
 [  -1  144  484 1936   -1   -1]
 [  -1 1764  784  256   -1   -1]]
